instituto/Segundo Año/Laboratotios.NET/Laboratorio3/Laboratorio3/Models/Envasado.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Web;

namespace Laboratorio3.Models
{
    public class Envasado
    {
        public Envasado()
        {
            Nombre = "";
            Descripcion = "";
        }

        [DisplayName("Nombre")]
        public string Nombre { get; set; }

        [DisplayName("Descripcion")]
        public string Descripcion { get; set; }
    }
}

instituto/Segundo Año/Laboratotios.NET/Laboratorio3/Laboratorio3/Models/Lista.cs
using System;
using System.Collections.Generic;
using Laboratorio3.Models;
using System.Linq;
using System.Web;

namespace Laboratorio3.Models
{
    public class Lista
    {
        public List<Perecible> Perecible;
        public List<NoPerecible> NoPerecible;

        public Lista()
        {
            this.NoPerecible = new List<NoPerecible>();
            NoPerecible prod = new NoPerecible();
            prod.Id = 0;
            prod.Nombre = "Pan";
            prod.CodBarra = "001001111";
            prod.Precio = 200;
            prod.Cantidad = 2;
            prod.Estado = true;
            prod.Envasado.Nombre = "Vacio";
            prod.Envasado.Descripcion = "xxxxx";

            this.NoPerecible.Add(prod);

            this.Perecible = new List<Perecible>{
                new Perecible()
                {
                    Id = 0,
                    Nombre = "Pan",
                    CodBarra = "John",
                    Precio = 18,
                    Cantidad = 10,
                    Estado = true,
                    FechaVencimiento = new DateTime(2019,4,25)
                }
            };

        }
        /// <summary>
        /// Perecible
        /// </summary>
        
        public void agregarPerecible(Perecible p)
        {
            this.Perecible.Add(p);
        }
        public Perecible GetPerecible(int id)
        {
            return this.Perecible[id];
        }
        /// <summary>
        /// No Perecible
        /// </summary>
        public void agregarNoPerecible(NoPerecible p)
        {
            this.NoPerecible.Add(p);
        }

        public NoPerecible GetNoPerecible(int id)
        {
            return this.NoPerecible[id];
        }
    }
}

instituto/Segundo Año/Laboratotios.NET/Laboratorio3/Laboratorio3/Models/NoPerecible.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;
using System.Linq;
using System.Web;

namespace Laboratorio3.Models
{
    public class NoPerecible : Producto 
    {

        private Envasado envasado;
        public NoPerecible()
        {
            envasado = new Envasado();
        }

        [DisplayName("Envasado")]
        public Envasado Envasado { get => envasado; set => envasado = value; }


    }
}

instituto/Segundo Año/Laboratotios.NET/Laboratorio3/Laboratorio3/Models/Perecible.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;
using System.Linq;
using System.Web;

namespace Laboratorio3.Models
{
    public class Perecible : Producto
    {

        [Required]
        [DisplayName("dias")]
        public int Dias { get => GetDias(); private set => SetDias(); }

        [Required]
        [DisplayName("Fecha de vencimiento")]
        public DateTime FechaVencimiento { get; set; }
        

        private int GetDias()
        {
            TimeSpan tem = this.FechaVencimiento - DateTime.Now;
            return tem.Days;
        }

        private void SetDias()
        {

        }

    }
}

instituto/Segundo Año/Laboratotios.NET/Laboratorio3/Laboratorio3/Models/Producto.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Web;

namespace Laboratorio3.Models
{
    public class Producto
    {
        private int id;

        [DisplayName("ID")]
        public int Id { get => id; set => id = value; }

        [DisplayName("Nombre")]
        public string Nombre { get; set; }

        [DisplayName("Codigo de Barra")]
        public string CodBarra { get; set; }

        [DisplayName("Precio")]
        public int Precio { get; set; }

        [DisplayName("Cantidad disponible")]
        public int Cantidad { get; set; }

        [DisplayName("Estado")]
        public bool Estado { get; set; }
    }
}

instituto/Segundo Año/Laboratotios.NET/Laboratorio3/Laboratorio3/Controllers/HomeController.cs
using Laboratorio3.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Laboratorio3.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
           
            string keyConfig = ConfigurationManager.AppSettings["titulo"];
            ViewBag.titulo = keyConfig;
            return View();
        }
    }
}

instituto/Segundo Año/Laboratotios.NET/Laboratorio3/Laboratorio3/Controllers/NoPerecibleController.cs
using Laboratorio3.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Laboratorio3.Controllers
{
    public class NoPerecibleController : Controller
    {

        public static Lista lista = new Lista();

        public ActionResult Listar()
        {
            return View(lista.NoPerecible);
        }
        public ActionResult Detalle(int id)
        {
            NoPerecible prod = lista.GetNoPerecible(id); 
            return View(prod);
        }
        public ActionResult Crear()
        {
            return View();
        }
        // POST: NoPerecible/Create
        [HttpPost]
        public ActionResult Crear(FormCollection FormCollection)
        {
            try
            {
                NoPerecible produc = new NoPerecible();
                produc.Id = lista.NoPerecible.Count;
                produc.Nombre = FormCollection["Nombre"];
                produc.CodBarra = FormCollection["CodBarra"];
                produc.Precio = int.Parse(FormCollection["Precio"]);
                produc.Cantidad = int.Parse(FormCollection["Cantidad"]);
                string na = FormCollection["Estado"];
                if (na.Equals("false"))
                    produc.Estado = false;
                else
                    produc.Estado = true;

                produc.Envasado.Nombre = FormCollection["Envasado.Nombre"];
                produc.Envasado.Descripcion = FormCollection["Envasado.Descripcion"];
                lista.agregarNoPerecible(produc);
                return Redirect("Listar");
            }
            catch
            {
                return View();
            }
        }
    }
}

instituto/Segundo Año/Laboratotios.NET/Laboratorio3/Laboratorio3/Controllers/PerecibleController.cs
using Laboratorio3.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Laboratorio3.Controllers
{
    public class PerecibleController : Controller
    {

        public static Lista lista = new Lista();

        public ActionResult Listar()
        {
            return View(lista.Perecible);
        }

        public ActionResult Detalle(int id)
        {
            Perecible prod = lista.GetPerecible(id);
            return View(prod);
        }
        
        public ActionResult Crear()
        {
            return View();
        }
        
        [HttpPost]
        public ActionResult Crear(FormCollection collection)
        {
            try
            {
                Perecible produc = new Perecible();

                produc.Id = lista.NoPerecible.Count;
                produc.Nombre = collection["Nombre"];
                produc.CodBarra = collection["CodBarra"];
                produc.Precio = int.Parse(collection["Precio"]);
                produc.Cantidad = int.Parse(collection["Cantidad"]);
                string na = collection["Estado"];
                if (na.Equals("false"))
                    produc.Estado = false;
                else
                    produc.Estado = true;
                produc.FechaVencimiento = DateTime.Parse(collection["FechaVencimiento"]);

                lista.agregarPerecible(produc);

                return Redirect("Listar");    
            }
            catch
            {
                return View();
            }
        }
    }
}

instituto/Segundo Año/Laboratotios.NET/Laboratorio3/Laboratorio3/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1 style="font-size:14;color:black">@ViewBag.titulo</h1>
    <p class="lead">Primera Fase de Desarrollo Aplicación Web MVC, creación de interfaz y menú con routing.</p>
    @*<p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>*@
</div>

<div class="row">
    <div class="col-md-4" style="background-color:beige">
        <h2>Paso 1 (20 puntos)</h2>
        <p>
            Crear Nueva aplicación ASP.NET MVC.<br />
            Modificar el Menú con los ítems: Inicio, Acerca, Contáctanos, Productos y además de cambiar el nombre por defecto a la aplicación. Esto se debe hacer desde el Layout de la solución.<br />
            El nombre de la aplicación, se debe escribir como AppSetting dentro del archivo WebConfig.
        </p>
        @*<p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>*@
    </div>
    <div class="col-md-4" style="background-color:azure">
        <h2>Paso 2 (20 puntos)</h2>
        <p>
            Dentro de la carpeta de modelo, debe crear el siguiente modelo de datos:<br />
            Producto<br />
            &nbsp;&nbsp;&nbsp;&nbsp;Propiedades:<br />
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;• Nombre → String<br />
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;• Codigo de Barra → String<br />
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;• Precio → int<br />
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;• Cantidad Disponible→ int<br />
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;• Estado → bool (indica si el producto está
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;disponible)<br /><br />
            ProductoPerecible (hace herencia del objeto Producto)<br />
            &nbsp;&nbsp;&nbsp;&nbsp;Propiedades:<br />
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;• Fecha de Vencimiento → Date<br />
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;• DiasParaVencer →Int ( Set Privado, se debe setear
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;solo tomando la fecha de vencimiento y la fecha
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;actual )<br />
            <br />
            ProductoNoPerecible (hace herencia del objeto Producto)<br />
            &nbsp;&nbsp;&nbsp;&nbsp;Propiedades:<br />
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;• Tipo de Envasado → Envasado<br /><br />
            Envasado<br />
            Propiedades:<br />
            &nbsp;&nbsp;&nbsp;&nbsp;• Nombre →String<br />
            &nbsp;&nbsp;&nbsp;&nbsp;• Descripcion→String<br />
            <br />
            Agregar la librería System.ComponentModel.DataAnnotations, al código de su clase y utilizar las etiquetas Display Name, String Length y Required ( para todos las propiedades)<br />

        </p>
        @*<p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>*@
    </div>
    <div class="col-md-4" style="background-color:beige">
        <h2>Paso 3 (20 puntos)</h2>
        <p>
            Implemente las vistas que permitan listar todos los productos, además que en esta lista
            permita seleccionar un producto y ver sus características.<br />
            Agregar opción de agregar nuevo producto.
        </p>
        @*<p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>*@
    </div>
</div>

instituto/Segundo Año/Laboratotios.NET/Laboratorio3/Laboratorio3/Views/NoPerecible/Crear.cshtml
@model Laboratorio3.Models.NoPerecible

@{
    ViewBag.Title = "";
}

<h2>Crear producto no perecible</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.CodBarra, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.CodBarra, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.CodBarra, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Precio, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Precio, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Precio, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Cantidad, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Cantidad, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Cantidad, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Estado, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.Estado)
                @Html.ValidationMessageFor(model => model.Estado, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Envasado, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Envasado.Nombre, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Envasado.Nombre, "", new { @class = "text-danger" }) <br />
            @Html.EditorFor(model => model.Envasado.Descripcion, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Envasado.Descripcion, "", new { @class = "text-danger" })
        </div>
    </div>
    @*public NoPerecible()
    {
    Envasado envasado = new Envasado("","");
    }*@

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Crea" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Volver a la lista", "Listar")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

instituto/Segundo Año/Laboratotios.NET/Laboratorio3/Laboratorio3/Views/NoPerecible/Detalle.cshtml
@model Laboratorio3.Models.NoPerecible

@{
    ViewBag.Title = "DetalleNoPerecible";
}

<h2>Detalle de Producto No Perecible</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CodBarra)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CodBarra)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Precio)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Precio)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Cantidad)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Cantidad)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Estado)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Estado)
        </dd>
        <dt>
            <br />
            @Html.DisplayNameFor(model => model.Envasado) <br />
        </dt>
        <dt style="font-weight:normal" >
            @Html.DisplayNameFor(model => model.Envasado.Nombre) <br />
            @Html.DisplayNameFor(model => model.Envasado.Descripcion) <br />
        </dt>
        <dd>
            <br /> <br />
            @Html.DisplayFor(model => model.Envasado.Nombre) <br />
            @Html.DisplayFor(model => model.Envasado.Descripcion)
        </dd>
    </dl>
</div>
<p>
    @*@Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |*@
    @Html.ActionLink("Volver A La Lista", "Listar")
</p>

instituto/Segundo Año/Laboratotios.NET/Laboratorio3/Laboratorio3/Views/NoPerecible/Listar.cshtml
@model IEnumerable<Laboratorio3.Models.NoPerecible>

@{
    ViewBag.Title = "ListarNoPerecible";
}

<h2>ListarNoPerecible</h2>

<p>
    @Html.ActionLink("Nuevo Producto", "Crear")
</p>
<table class="table">
    <tr>
        <th rowspan="2" style="text-align:center;vertical-align:middle">
            @Html.DisplayNameFor(model => model.Id)
        </th>
        <th rowspan="2" style="text-align:center;vertical-align:middle">
            @Html.DisplayNameFor(model => model.Nombre)
        </th>
        <th rowspan="2" style="text-align:center;vertical-align:middle">
            @Html.DisplayNameFor(model => model.CodBarra)
        </th>
        <th rowspan="2" style="text-align:center;vertical-align:middle">
            @Html.DisplayNameFor(model => model.Precio)
        </th>
        <th rowspan="2" style="text-align:center;vertical-align:middle">
            @Html.DisplayNameFor(model => model.Cantidad)
        </th>
        <th rowspan="2" style="text-align:center;vertical-align:middle">
            @Html.DisplayNameFor(model => model.Estado)
        </th>
        <th rowspan="1" colspan="2" style="text-align:center;vertical-align:middle">
            @Html.DisplayNameFor(model => model.Envasado)
        </th>
    </tr>
    <tr>
        <td colspan="1" rowspan="1" style="text-align:center">
            @Html.DisplayNameFor(model => model.Envasado.Nombre)
        </td>
        <td colspan="1" rowspan="1" style="text-align:center">
            @Html.DisplayNameFor(model => model.Envasado.Descripcion)
        </td>
    </tr>

    @foreach (var item in Model)
    {
        <tr>

            <td style="text-align:center">
                @Html.DisplayFor(modelItem => item.Id)
            </td>

            <td style="text-align:center">
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            
            <td style="text-align:center">
                @Html.DisplayFor(modelItem => item.CodBarra)
            </td>
            <td style="text-align:center">
                @Html.DisplayFor(modelItem => item.Precio)
            </td>
            <td style="text-align:center">
                @Html.DisplayFor(modelItem => item.Cantidad)
            </td>
            <td style="text-align:center">
                @Html.DisplayFor(modelItem => item.Estado)
            </td>
            <td style="text-align:center">
                @Html.DisplayFor(modelItem => item.Envasado.Nombre)
            </td>
            <td style="text-align:center">
                @Html.DisplayFor(modelItem => item.Envasado.Descripcion)
            </td>



            <td>
                @*@Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |*@
                @Html.ActionLink("Detalle", "Detalle", new { id = item.Id }) @*|
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })*@
            </td>
        </tr>
    }

</table>

instituto/Segundo Año/Laboratotios.NET/Laboratorio3/Laboratorio3/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar">holaaa1</span>
                    <span class="icon-bar">holaaa2</span>
                    <span class="icon-bar">holaaa3</span>
                </button>
                
                <div class="navbar-brand">
                    LABORATORIO 3
                </div>
                
                @*@Html.ActionLink( "LABORATORIO3", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })*@
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
                    
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Listar <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Perecibles", "Listar", "Perecible")</li>
                            @*<li><a href="#"> Perecibles</a></li>*@
                            <li role="separator" class="divider"></li>
                            <li>@Html.ActionLink("No Perecibles", "Listar", "NoPerecible")</li>
                            @*<li><a href="#"> No Perecibles</a></li>*@
                        </ul>
                    </li>

                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Maximiliano Moraga (.NET)</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>